<a href="https://colab.research.google.com/github/shimaneesh2008-pixel/EDA---25BAI0007/blob/main/EDA2_25BAI0007_21_7_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1NT = pd.DataFrame({ 'Cinema': ['Pushpa', 'Bahubali', 'Saaho', 'Salaar', 'Kalki', 'Rebel', 'IT', 'Obsession', 'HIT', 'U-TURN', 'ABCD'],
                       'Collection Net(in crores)' : [220, 10000, 8554, 5155, 7981, 9100, 560, 132, 852, 573, 992]})
df2NT =  pd.DataFrame({'Cinema': ['10 Raw (2016)', '9 Go (1999)', '8 Up (2009)', '7 It (2017)', '6 M (1931)', '5 May (2002)' ,'4 Ben (1972)', '3 Pi (1998)'],
                       'Collection Net(in crores)': [98, 93, 44, 77, 69, 56, 31, 53]})

df1GR =  pd.DataFrame({ 'Cinema': ['Pushpa', 'Bahubali', 'Saaho', 'Salaar', 'Kalki', 'Rebel', 'IT', 'Obsession', 'HIT', 'U-TURN', 'ABCD'],
                       'Collection Gross(in crores)' : [320, 10100, 8654, 5255, 8081, 9200, 660, 232, 952, 673, 1092]})
df2GR =  pd.DataFrame({'Cinema': ['10 Raw (2016)', '9 Go (1999)', '8 Up (2009)', '7 It (2017)', '6 M (1931)', '5 May (2002)' ,'4 Ben (1972)', '3 Pi (1998)'],
                       'Collection Gross(in crores)': [93, 44, 78, 97, 87, 89, 39, 43]})

In [ ]:
dfNT = pd.concat([df1NT, df2NT], ignore_index=True)
dfGR = pd.concat([df1GR, df2GR], ignore_index=True)

In [ ]:
df = pd.concat([dfGR, dfNT], axis=1)
df

,Cinema,Collection Gross(in crores),Cinema,Collection Net(in crores)
0,Pushpa,320,Pushpa,220
1,Bahubali,10100,Bahubali,10000
2,Saaho,8654,Saaho,8554
3,Salaar,5255,Salaar,5155
4,Kalki,8081,Kalki,7981
5,Rebel,9200,Rebel,9100
6,IT,660,IT,560
7,Obsession,232,Obsession,132
8,HIT,952,HIT,852
9,U-TURN,673,U-TURN,573
10,ABCD,1092,ABCD,992
11,10 Raw (2016),93,10 Raw (2016),98
12,9 Go (1999),44,9 Go (1999),93
13,8 Up (2009),78,8 Up (2009),44
14,7 It (2017),97,7 It (2017),77
15,6 M (1931),87,6 M (1931),69
16,5 May (2002),89,5 May (2002),56
17,4 Ben (1972),39,4 Ben (1972),31
18,3 Pi (1998),43,3 Pi (1998),53

In [ ]:
dfNT = pd.concat([df1NT, df2NT], ignore_index=True)
dfGR = pd.concat([df1GR, df2GR], ignore_index=True)

df = dfNT.merge(dfGR, how='right')
df

           Cinema  Collection Net(in crores)  Collection Gross(in crores)
0          Pushpa                        220                          320
1        Bahubali                      10000                        10100
2           Saaho                       8554                         8654
3          Salaar                       5155                         5255
4           Kalki                       7981                         8081
5           Rebel                       9100                         9200
6              IT                        560                          660
7       Obsession                        132                          232
8             HIT                        852                          952
9          U-TURN                        573                          673
10           ABCD                        992                         1092
11  10 Raw (2016)                         98                           93
12    9 Go (1999)                         93                           44
13    8 Up (2009)                         44                           78
14    7 It (2017)                         77                           97
15     6 M (1931)                         69                           87
16   5 May (2002)                         56                           89
17   4 Ben (1972)                         31                           39
18    3 Pi (1998)                         53                           43

In [ ]:
dfNT = pd.concat([df1NT, df2NT], ignore_index=True)
dfGR = pd.concat([df1GR, df2GR], ignore_index=True)

df = dfNT.merge(dfGR, how='inner')
df

           Cinema  Collection Net(in crores)  Collection Gross(in crores)
0          Pushpa                        220                          320
1        Bahubali                      10000                        10100
2           Saaho                       8554                         8654
3          Salaar                       5155                         5255
4           Kalki                       7981                         8081
5           Rebel                       9100                         9200
6              IT                        560                          660
7       Obsession                        132                          232
8             HIT                        852                          952
9          U-TURN                        573                          673
10           ABCD                        992                         1092
11  10 Raw (2016)                         98                           93
12    9 Go (1999)                         93                           44
13    8 Up (2009)                         44                           78
14    7 It (2017)                         77                           97
15     6 M (1931)                         69                           87
16   5 May (2002)                         56                           89
17   4 Ben (1972)                         31                           39
18    3 Pi (1998)                         53                           43

In [ ]:
dfNT = pd.concat([df1NT, df2NT], ignore_index=True)
dfGR = pd.concat([df1GR, df2GR], ignore_index=True)

df = dfNT.merge(dfGR, how='left')
df

           Cinema  Collection Net(in crores)  Collection Gross(in crores)
0          Pushpa                        220                          320
1        Bahubali                      10000                        10100
2           Saaho                       8554                         8654
3          Salaar                       5155                         5255
4           Kalki                       7981                         8081
5           Rebel                       9100                         9200
6              IT                        560                          660
7       Obsession                        132                          232
8             HIT                        852                          952
9          U-TURN                        573                          673
10           ABCD                        992                         1092
11  10 Raw (2016)                         98                           93
12    9 Go (1999)                         93                           44
13    8 Up (2009)                         44                           78
14    7 It (2017)                         77                           97
15     6 M (1931)                         69                           87
16   5 May (2002)                         56                           89
17   4 Ben (1972)                         31                           39
18    3 Pi (1998)                         53                           43

In [ ]:
import numpy as np
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [ ]:
stacked = dframe1.stack()
stacked

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [ ]:
stacked.unstack()

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [ ]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN